trigger:
- main
- staging/*
- next_stable
- 20*

pr:
- main
- next_stable
- 20*

variables:
  runCondition: true
  targetBranch: $[ variables['System.PullRequest.TargetBranchName'] ]

jobs:
- job: LinuxBuilds
  strategy:
    matrix:
      astyle:
        imageName: 'ubuntu-latest'
        BUILD_TYPE: astyle
        TARGET_BRANCH: '$(targetBranch)'
      cppcheck:
        imageName: 'ubuntu-latest'
        BUILD_TYPE: cppcheck
        TARGET_BRANCH: '$(targetBranch)'
      drivers:
        imageName: 'ubuntu-latest'
        BUILD_TYPE: drivers
      documentation:
        imageName: 'ubuntu-latest'
        BUILD_TYPE: documentation
        UPDATE_GH_DOCS: 0
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    condition: eq(variables.runCondition, true)
    fetchDepth: 50
    clean: true
    persistCredentials: true
  - script: ./ci/run_build.sh
    condition: eq(variables.runCondition, true)
    displayName: 'Run $(BUILD_TYPE)'
